# This file is used to set up the parameters for data loading, logging, and other settings.

data_source:
  raw_path: "./data/raw/opiod_raw_data.csv" # Relative or absolute path to data file
  processed_path: "./data/processed/opiod_processed_data.csv" # Path to save processed data
  type: "csv"                      # Data file type: 'csv' or 'excel'
  sheet_name: "Sheet1"             # Only used if type == 'excel'
  delimiter: ","                   # Only used if type == 'csv'
  header: 0                        # Row number to use as column names (0-indexed), update if needed
  encoding: "utf-8"                # File encoding (utf-8 covers most cases)

logging:
  level: "INFO"                         # Logging level: DEBUG (verbose), INFO (default), WARNING, ERROR, CRITICAL
  log_file: "./logs/main.log"    # File path for log output
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"  # Log message format
  datefmt: "%Y-%m-%d %H:%M:%S"          # Date format for logs

data_split:
  test_size: 0.2
  valid_size: 0.2
  random_state: 42

model:
  active: decision_tree  # Options: decision_tree, logistic_regression, random_forest

  decision_tree:
    save_path: models/decision_tree.pkl
    params:
      max_depth: 4
      random_state: 42

  logistic_regression:
    save_path: models/logistic_regression.pkl
    params:
      penalty: l2
      solver: lbfgs
      random_state: 42
      max_iter: 200

  random_forest:
    save_path: models/random_forest.pkl
    params:
      n_estimators: 100
      max_depth: 5
      random_state: 42

raw_features:  
  - rx_ds
  - A
  - B
  - C
  - D
  - E
  - F
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - R
  - S
  - T
  - V


features:
  # List all columns to use as features (update dynamically if engineered features added)
  - rx_ds_norm
  - rx_ds_bucket_Q1
  - rx_ds_bucket_Q2
  - rx_ds_bucket_Q3
  - rx_ds_bucket_Q4
  - A
  - B
  - C
  - D
  - E
  - F
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - R
  - S
  - T
  - V

target: OD

metrics:
  - Accuracy
  - Precision (PPV)
  - Recall (Sensitivity)
  - Specificity
  - F1 Score
  - Negative Predictive Value (NPV)
  - ROC AUC

preprocessing:
  rx_ds:
    normalization: minmax           # or 'zscore'
    bucketize: true                 # set to false to disable bucketing
    n_buckets: 4
    bucket_labels: [Q1, Q2, Q3, Q4]
    one_hot_encode_buckets: true    # set to false to skip dummy vars
    rename_columns:
      "rx ds": rx_ds                # key: old name, value: new name

artifacts:
  preprocessing_pipeline: models/preprocessing_pipeline.pkl
